spring:
  main:
    log-startup-info: true
  output:
    ansi:
      enabled: ALWAYS
  sql.init.mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jackson.default-property-inclusion: NON_NULL
logging.level:
  root: INFO
  ru.yandex.practicum.filmorate: INFO
  org.zalando.logbook: TRACE

